### ISSUE TITLE
Neural Blinder/Class Interrupt overlap

### ISSUE THREAD

**Issue by jrsteensen** [rocketcatmultiverse/starmourn-nexus-basher#19]
Can you add a config toggle for having the neural blinder artifact, and skipping firing an interrupt skill if the neural blinder artifact interrupts the windup? Also, add alternative trigger for when the typo in the echo is fixed, i.e. `distrupts` becomes `disrupts`.

```
Rearing back on its powerful hind legs and muscular, prehensile tail, the moss lizard coils itself tight, ready to spring.
A ferociously toothed moss lizard loses its concentration.
You: Neural Blinder -> a ferociously toothed moss lizard.
Detecting a high intensity attack aimed your way, your Neural Blinder fires up and distrupts a ferociously toothed moss lizard's concentration with a high-intensity neural signal.

You have recovered your balance.

You: MWP Netlaunch -> a ferociously toothed moss lizard.
You launch a nanofilament net at a ferociously toothed moss lizard.
Balance used: 2.70s.

You can again use the Neural Blinder artifact power.
```

**Comment by rocketcatmultiverse** [comment]
Hmm. Neural blinder should be working... Did this all happen within the span of 50ms or so, or did neural blinder fire like, 1s before bal recovery?

**Comment by diegojcastro** [comment]
With the latest changes where IH fires on windup message and interrupts are only sent on "channeling an attack" from IH output, this issue should in theory be fixed now, and limited testing suggests it has.
