### ISSUE TITLE
interrupt malfunction

### ISSUE THREAD

**Issue by zombilicious** [rocketcatmultiverse/starmourn-nexus-basher#4]
Not sure why it's doing this, but during bashing in the Coriolis, I noticed that it's sending this function as a chunk of text and not actually trying to use it as a function:

`Balance used: 1.00s.

function(){
	if (!nb.interrupt) return false;
	switch (nb.class) {
		case "Engineer":
			return 'bot swing '+nb.tar;
		case "Scoundrel":
			if (nb.bullets === 0 ) {
				return "guile pocketsand "+nb.tar;
			} else {
				return "gun pointblank "+nb.tar;
			} 
		case "BEAST":
			return "mwp netlaunch "+nb.tar;
		case "Fury":
			return "kith fever "+nb.tar;
		case "Nanoseer":
			return "nano eyestrike "+nb.tar;
		default:
			nb.error("Invalid class "+nb.class+" provided to nb.sendHeal");
			return false;
	}
}`

**Comment by rocketcatmultiverse** [comment]
Fixed! NBRELOAD in about 5 minutes. Thanks for the report!
